version: "3.8"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    # volumes:
    #   - ./:/usr/src/app:ro
    # env_file:
    #   - ./.env
    environment:
      - RDS_HOSTNAME=postgres
      - RDS_PORT=5432
      - RDS_PASSWORD=
      - RDS_DB_NAME=directed
      - RDS_USERNAME=postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  postgres:
    image: postgres
    # ports:
    #   - 5432:5432
    environment:
      #- POSTGRES_PASSWORD=
      - POSTGRES_DB=directed
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-db:/var/lib/postgrsql/data

volumes:
  postgres-db: