version: "3.8"
services:
  api:
    image: bubblyc/directed-backend #pull from docker hub from production environment
    #build: .
    depends_on:
      - postgres
    ports:
      - 80:8000

    env_file:
      - ./.env
    
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${RDS_PASSWORD}
      - POSTGRES_DB=${RDS_DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgrsql/data

volumes:
  postgres-db: