branch-defaults:
  main:
    environment: directed-backend-app-env
    group_suffix: null
environment-defaults:
  directed-backend-app-env:
    branch: null
    repository: null
global:
  application_name: directed-backend-app
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
